site:
  datasource_driver: com.mysql.cj.jdbc.Driver
  datasource_url: jdbc:mysql://localhost:3307/pybbs?serverTimezone=GMT%2B8&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8
  datasource_username: xuechun
  datasource_password: 123456

# 想看mybatis执行的sql的时候，去掉下面这段的注释
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl